### ISSUE TITLE
Possible FSA-Style update Bug

### ISSUE THREAD

**Issue by bignamehere** [USDA-FSA/proto#29]
There seems to be an issue when updating to version 2.7.0+ with Proto.

Doing research.

**Comment by bignamehere** [comment]
![Snag_ad7adda](https://user-images.githubusercontent.com/2124049/149183706-532ea30f-ccb1-4900-bace-82537fbff920.png)

**Comment by bignamehere** [comment]
![Snag_ad9bbbb](https://user-images.githubusercontent.com/2124049/149184042-5d930f88-d745-425a-988f-cbdcaefd1f38.png)

**Comment by bignamehere** [comment]
Solution is to update FSA Style Dependency after new patch is released

**Comment by francisrupert** [comment]
@bignamehere 

`2.7.2` is published, resolving https://github.com/USDA-FSA/fsa-style/issues/556
